### ISSUE TITLE
behaviour with existing Timer 

### ISSUE THREAD

**Issue by dudz40** [mattdavis90/node-tado-client#40]
Hi Matt, got a question, when TADO has a running action with a Timer, and I need to change temp or another attribute during that action, it looks like I it will change to next-time-block as termination, what i need is that it leaves the termination with the time duration as is. Can that be done?

**Comment by mattdavis90** [comment]
Hi, at the minute if the `termination` option isn't set then it defaults to "manual" which I think means you need to manually clear the overlay, rather than next time-block. I've just had a play around on app.tado.com and it looks as though their website sends the entire payload each time (calculating the time offset in your browser). This makes me think there isn't a way of sending just the temperature as an update. I think we have two options, either expect the user of the library to perform a getState API call, read the overlays, track the time and update the overlay with the temperature and timeout accordingly (as the Tado website does) or, alternatively, we could change the behaviour of the library so that it doesn't default to "manual" when an option isn't given and instead does the getState and tracking on behalf of the user.

**Comment by dudz40** [comment]
Was afraid i had to get and set the duration ;-) thanks!
